name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Change to your branch name if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Site Content
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./  # If your site content is in a subdirectory, adjust this path

deployment:
  runs-on: ubuntu-latest
  needs: build-and-deploy
  steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
